### ISSUE TITLE
DbFirst model generation performance issue

### ISSUE THREAD

**Issue by davidda** [bubibubi/JetEntityFrameworkProvider#14]
Generating a model from my db seemed to take indefinitely. After 30mins (with VS using 100% of one CPU core) I killed the process. Next try I debugged the process and found the cause:

The function StoreSchemaDefinitionRetrieve.GetFieldRow executes an inefficient statement for all(?) tables and views in the db: `select * from tbl where 1=2`

The issue is that for views this will evaluate all rows. I found that doing this instead is much faster: `select top 1 * from tbl` (so top instead of where)

I tried to generate again and now it takes less than one minute.

The other concern of course is, why would it even execute that statement for an object I have not chosen for model generation... However, with the improved speed this is not of a concern to me.

**Comment by bubibubi** [comment]
Thanks for the suggestion (Can't understand why top 1 takes less than where 1 = 2).



I'm generating data for system tables that will be used by EF scavenging process. I don't know wich tables have been chosen.

**Comment by bubibubi** [comment]
Probably the problem is different.
There is a difference but is about 4%.

This is my tests:

900.000 records on a table.
File size .8Gb
Without disposing connection on every table retrieve
Select 5000 Where 1=2 get data reader started at 18/09/2017 16:36:28 is finishing at 18/09/2017 16:36:34 after 5,5188356
Select 5000 Where 1=2 get table structure started at 18/09/2017 16:36:34 is finishing at 18/09/2017 16:36:42 after 8,4189373
Select 5000 Top 1 get data reader started at 18/09/2017 16:36:42 is finishing at 18/09/2017 16:36:47 after 4,7737327
Select 5000 Top 1 get table structure started at 18/09/2017 16:36:47 is finishing at 18/09/2017 16:36:55 after 8,5812101
Select 5000 Top 1 Where 1=2 get data reader started at 18/09/2017 16:36:55 is finishing at 18/09/2017 16:37:00 after 5,0103997
Select 5000 Top 1 Where 1=2 get table structure started at 18/09/2017 16:37:00 is finishing at 18/09/2017 16:37:09 after 8,5117551

Disposing connection on every table retrieve
Select 60 Where 1=2 get table structure (Dispose connection) started at 18/09/2017 16:27:38 is finishing at 18/09/2017 16:27:41 after 3,6939221
Select 60 Top 1 get table structure (Dispose connection) started at 18/09/2017 16:27:41 is finishing at 18/09/2017 16:27:45 after 3,59952
