### ISSUE TITLE
DB First

### ISSUE THREAD

**Issue by TheColonel2688** [bubibubi/JetEntityFrameworkProvider#4]
No one creates new Jet Databases anymore, the only value this tool has is for working with existing databases. JetEntityFrameworkProvider needs to support DB first, even in a limited capacity. So if there is anything you can do to help in that realm it would be greatly appreciated.

Question 1: Was the schema retriever ever functional at all? even in a limited capacity? 

Question 2: Is there a way to force Entity Framework to use existing tables, instead of trying to create new ones? I have tried manually recreating the model in code, however, I get an error: "System.Data.OleDb.OleDbException: 'Table 'Component' already exists.'" for the table model, I have recreated.

**Comment by bubibubi** [comment]
Answer 1: There are the code to retrieve all the schema. The problem is that at a certain point EF generates a too complex query so Jet cannot resolve it.

Answer 2: You can disable migration in EF so it will use the already existing database. I suggest also to write a test to check mappings (because EF will not check for errors).


You can also post question on Stack Overflow.
