### ISSUE TITLE
Known limitations of JetEntityFramework??? Pivots?

### ISSUE THREAD

**Issue by raytrask** [bubibubi/JetEntityFrameworkProvider#9]
Hey @bubibubi,

Love your work.  Thanks for all you've done.  

Now on to my question,  I seem to remember in an old version of the documentation you had listed some limitations of the framework.  I can't seem to find where those limitations are listed (was it CrossTab and/or timestamp related I don't remember??). Either you fixed them were or I just can't find where you had it.   Reason I ask is that I wanted to use Pivot operations EF and for some reason I thought it was limited.   I will probably go with [this approach anyway](https://code.msdn.microsoft.com/windowsdesktop/CSEFPivotOperation-cbdd79db) but I thought I would ask just the same.  

By the way, I'd be glad to help document the answer if you like.

Thanks again.

**Comment by bubibubi** [comment]
Hi @raytrask,
I'm happy you are using the provider.

Actually I removed all the limitations. If you use a lot of Include you could have problems (Microsoft Access limitations) otherwise there are not known bugs.
You could try to implement pivots using just the provider then, if it does not work I can try to fix it.

Any help is really appreciated!!!

Thanks to you!

**Comment by raytrask** [comment]
Knowing .you're work, I'm not surprised you removed the limitations!!!  I will let you know if I find any!.

**Comment by raytrask** [comment]
Feel free to close this.  

Thanks
